#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket daemon"
        # Start your application in daemon mode
        start-stop-daemon -S -g root -n aesdsocket -a /usr/bin/aesdsocket -- -d

        sleep 2
        ;;
    stop)
        echo "Stopping aesdsocket daemon"
        # Terminate your application gracefully (triggers SIGTERM)
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0